// Package brand owns the Pantegnos mark.
//
// internal/brand/logo.svg is the single source of truth. Everything else that
// needs the mark derives from it, or is checked against it:
//
//   - the Android interface inlines LogoSVG via the template
//   - the web decryptor serves a copy, which TestWebCopyMatches guards
//   - the Android launcher drawable is a VectorDrawable, so its path data is
//     compared against the SVG by TestAndroidVectorMatches
//   - the Windows binary embeds icon.ico, regenerated by tools/icon
//
// Keeping the geometry in one place is the point: a hexagon frame around a lock
// with a keyhole, identical in the launcher, the browser tab, the web header and
// the Explorer icon.
package brand

import (
	_ "embed"
	_ "image/png" // registers the PNG decoder used to validate the favicons
)

//go:embed logo.svg
var logoSVG string

//go:embed logo-solid.svg
var logoSolidSVG string

// LogoSVG is the mark themed by the embedding page: its colours are custom
// properties, so one file serves both the light and the dark palettes.
func LogoSVG() string { return logoSVG }

// LogoSolidSVG is the same geometry with literal colours, for places that
// cannot read a stylesheet, such as a favicon.
func LogoSolidSVG() string { return logoSolidSVG }
