[versions]
agp = "8.13.2"
kotlin = "2.2.20"
coreKtx = "1.16.0"
activity = "1.10.1"
webkit = "1.14.0"
junit = "4.13.2"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-webkit = { group = "androidx.webkit", name = "webkit", version.ref = "webkit" }
junit = { group = "junit", name = "junit", version.ref = "junit" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
